### ISSUE TITLE
uh oh. RangeError: End Date is invalid

### ISSUE THREAD

**Issue by keegansimyh** [Corvimae/timeloss.run#1]
What might cause that?

**Comment by Corvimae** [comment]
If you have an attempt with a start date but not an end date this will happen. I haven't filtered runs like that out yet since I'm not sure exactly how an attempt like that happens and what exactly it means.

**Comment by keegansimyh** [comment]
Hmm, that doesn't seem to be the case with my splits; as far as I can see all 107 attempts have an end date.
[Super Mario Galaxy 2 - 242 Stars (3).lss.zip](https://github.com/Corvimae/timeloss.run/files/6697093/Super.Mario.Galaxy.2.-.242.Stars.3.lss.zip)

**Comment by Corvimae** [comment]
Ah, this is because I didn't know how Livesplit formats pause durations longer than a day. Will fix, thank you!

**Comment by keegansimyh** [comment]
Awesome, thanks for making this and responding so quickly!
